# @package _global_
defaults:
  - /agent@agent: add_g1
  - /engine@engine: genesis
  - /robot@robot: g1
  - /task@task: pose
  - /distributed@distributed: ddp
  - _self_

mode: train
experiment_name: all_motions_8xh100
log_dir: logs/

task:
  enable_phase_obs: false
  enable_vel_obs: true
  enable_tar_obs: true
  tar_obs_steps: [1, 2, 3, 4]
  motion_file: "assets/motions/all_motions.yaml"
  sampler:
    num_segments: 900
agent:
  test_episodes: 5
  batch_size: 64
  steps_per_iter: 128
  update_epochs: 10
  grad_clip: 2.0
  model:
    actor_net: "fc_4layers_512units"
    critic_net: "fc_4layers_512units"
    disc_net: "fc_3layers_512units"
  optimizer:
    learning_rate: 2e-4
engine:
  num_envs: 8192
  enable_viewer: false
  enable_video_recording: false
